export { default as Login } from './login'
export { default as Home } from './home'
export { default as Signup } from './signup'
export { default as Review } from './review'
export { default as Detail } from './detail'